modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="biome_dimensions"
version="1.0.0"
displayName="Biome Dimensions"
displayURL="https://github.com/okil6dev/Okil6-s-Biome-Dimensions"
logoFile="logo.png"
credits="Made by okil6"
authors="okil6"
description="Each Dimension Is A Biome!"

# Start of user code block mod configuration
# End of user code block mod configuration


# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.biome_dimensions]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.190,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.biome_dimensions]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration